version: '3.8'

services:
  master:
    image: mysql:8
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: qr_gen
      MYSQL_USER: repl_user
      MYSQL_PASSWORD: repl_pass
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3307"
  
  slave:
    image: mysql:8
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: qr_gen
      MYSQL_USER: repl_user
      MYSQL_PASSWORD: repl_pass
    depends_on:
      - master
    volumes:
      - ./slave/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3308:3308"
